source 'https://rubygems.org'

gem 'berkshelf'
gem 'chef'
gem 'chef-zero'
gem 'foodcritic', '10.2.2'
gem 'foodcritic-junit'
gem 'inspec', '1.25.1'
gem 'kitchen-inspec', '0.19.0'
gem 'kitchen-transport-speedy'
gem 'kitchen-vagrant'
gem 'molinillo'
gem 'rainbow'
gem 'rubocop', '0.47.1'
gem 'rubocop-checkstyle_formatter'
gem 'rubocop-junit-formatter', '0.1.4', git: 'https://github.com/florian-asche/rubocop-junit-formatter'
gem 'test-kitchen', '1.17.0'
